// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVtqCEhtMeo47Q302cw_hZzxV9bediAU8',
    appId: '1:1062863828687:web:c5f059b3b40fd8114c69ba',
    messagingSenderId: '1062863828687',
    projectId: 'aplicativo-adocao-animais',
    authDomain: 'aplicativo-adocao-animais.firebaseapp.com',
    storageBucket: 'aplicativo-adocao-animais.firebasestorage.app',
    measurementId: 'G-PM9L84CHE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmesXWsic-_43_RvsK-gBb47JbJhTrrc8',
    appId: '1:1062863828687:android:5b02ef5d60af3d044c69ba',
    messagingSenderId: '1062863828687',
    projectId: 'aplicativo-adocao-animais',
    storageBucket: 'aplicativo-adocao-animais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Xn_wnNCkt0z5vwLWgJSlRVQyABgSAkE',
    appId: '1:1062863828687:ios:43e58935d8c0948b4c69ba',
    messagingSenderId: '1062863828687',
    projectId: 'aplicativo-adocao-animais',
    storageBucket: 'aplicativo-adocao-animais.firebasestorage.app',
    iosBundleId: 'com.example.educacenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Xn_wnNCkt0z5vwLWgJSlRVQyABgSAkE',
    appId: '1:1062863828687:ios:43e58935d8c0948b4c69ba',
    messagingSenderId: '1062863828687',
    projectId: 'aplicativo-adocao-animais',
    storageBucket: 'aplicativo-adocao-animais.firebasestorage.app',
    iosBundleId: 'com.example.educacenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVtqCEhtMeo47Q302cw_hZzxV9bediAU8',
    appId: '1:1062863828687:web:9f286d3e04ad53804c69ba',
    messagingSenderId: '1062863828687',
    projectId: 'aplicativo-adocao-animais',
    authDomain: 'aplicativo-adocao-animais.firebaseapp.com',
    storageBucket: 'aplicativo-adocao-animais.firebasestorage.app',
    measurementId: 'G-F81LF3XLRM',
  );
}
